@System_Uznawania_Przychodów_dla_dużej_korporacji_ABC_HostAddress = http://localhost:5129

GET {{System_Uznawania_Przychodów_dla_dużej_korporacji_ABC_HostAddress}}/weatherforecast/
Accept: application/json

###
